version: "3.8"

services:
  tic_tac_toe:
    build: .
    container_name: tic_tac_toe_service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python run.py
